name: Test Upload Artifact

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create a test file
        run: echo "Test" > test.txt
      - name: Upload Test File
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: test.txt
